name: Test Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dummy file
        run: |
          echo "هذا اختبار لـ artifact" > test.txt

      - name: Upload dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy_file
          path: test.txt
