# .github/workflows/flutter.yaml

name: Build Flutter APK & Upload Artifact

# شغّل العمل على أي دفع (push) إلى الفرع main أو عند تشغيله يدوياً
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # 1) خطوة checkout لسحب الكود
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # 2) خطوة إعداد بيئة Flutter
      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3) تثبيت dependencies وتوليد الأيقونات
      - name: "Install Dependencies & Generate Launcher Icons"
        run: |
          flutter pub get
          flutter pub run flutter_launcher_icons:main

      # 4) بناء تطبيق Android (APK) بإصدار release
      - name: "Build Release APK"
        run: |
          flutter build apk --release --no-sound-null-safety

      # 5) رفع ملف الـ APK كـ artifact لتمكين تنزيله من واجهة GitHub
      - name: "Upload APK Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: dalelk1_app_apk
          path: build/app/outputs/flutter-apk/app-release.apk
